# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

5. Посчитайте, сколько уникальных рецептов находится в датасете.

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

13. Выведите процент "простых" рецептов в датасете

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [9]:
# №1Файл minutes_n_ingredients.csv содержит информацию об идентификаторе рецепта, 
#времени его выполнения в минутах и количестве необходимых ингредиентов. 
#Считайте данные из этого файла в виде массива numpy типа int32, используя np.loadtxt. 
#Выведите на экран первые 5 строк массива.
import numpy as np
data=np.loadtxt('minutes_n_ingredients.csv', dtype=np.int32,delimiter=',')
print(data[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


In [39]:
# №2 Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.
import numpy as np
data=np.loadtxt('minutes_n_ingredients.csv', dtype=np.int32,delimiter=',')
data2=data[:,1:]
sred=np.mean(data2)
mini=np.min(data2)
maksi=np.max(data2)
med=np.median(data2)
print("Среднее значение по каждому столбцу (кроме первого):", sred,"\n"
      "Минимум по каждому столбцу (кроме первого):", mini,"\n"
      "Максимум по каждому столбцу (кроме первого):", maksi, "\n"
      "Медиана по каждому столбцу (кроме первого):",med)

Среднее значение по каждому столбцу (кроме первого): 10805.028485 
Минимум по каждому столбцу (кроме первого): 0 
Максимум по каждому столбцу (кроме первого): 2147483647 
Медиана по каждому столбцу (кроме первого): 13.0


In [38]:
# №3 Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля  𝑞0.75
q75=np.quantile(data[:,1], 0.75)
data[:,1]=np.where(data[:,1]>q75, q75, data[:,1])
print(data[:,1])

[60 25 10 ... 65  5 65]


In [60]:
# №4 Посчитайте, для скольких рецептов указана продолжительность, равная нулю. 
#Замените для таких строк значение в данном столбце на 1.
k=np.sum(data[:,1]==0)
if k>0:
    data[data[:,1]==0,1]=1
print(k)

0


In [61]:
# №5 Посчитайте, сколько уникальных рецептов находится в датасете
uni=np.unique(data[:,0])
kol=len(uni)
print(kol)

100000


In [62]:
# №6 Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?
uni2=np.unique(data[:,2])
kol2=len(uni2)
print("различных значений кол-ва ингредиентов", uni2, "\n",
     "количество различных ингредиентов", kol2, '\n')

различных значений кол-ва ингредиентов [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39] 
 количество различных ингредиентов 37 



In [66]:
# №7 Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.
k1=np.sum(data[:,2]<=5)
if k1>0:
    data5=data[data[:,2]<=5]
print(data5[:10])

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 [484223     18      4]
 [ 63150    250      4]
 [ 70453     25      4]
 [ 66842      2      4]
 [337928     55      4]
 [140245      5      5]
 [ 75313    603      5]]


In [69]:
# №8 Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. 
#Найдите максимальное значение этой величины для всего датасета
srin=data[:,2]/data[:,1]
maxk=np.max(srin)
print(srin[:20], "\n", maxk)

[0.26666667 0.28       0.6        1.2        0.23333333 0.175
 0.5        0.33333333 1.28571429 0.35       0.30769231 0.58333333
 0.12941176 0.6        0.2        0.66666667 0.58333333 0.03888889
 0.1625     0.3       ] 
 24.0


In [70]:
# №9 Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью
sor=data[data[:,1].argsort()[::-1]]
pr100=sor[:100]
srkin=np.mean(pr100[:,2])
print(srkin)

6.61


In [79]:
# №10 Выберите случайным образом и выведите информацию о 10 различных рецептах
ra=np.random.default_rng()
ind=ra.choice(len(data), 10, replace=False)
rr=data[ind]
for i in rr:
    print(i)

[77992   130    12]
[84702    10     5]
[229131     30      8]
[306770    100     15]
[238571    260      6]
[441914     20     11]
[392171     60     12]
[49846    70    11]
[441656     45      7]
[423072      2      3]


In [84]:
# №11 Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.
sredn=np.mean(data[:,2])
kk=sum(data[:,2]<sredn)
vsego=len(data)
print((kk/vsego)*100)

58.802


In [87]:
# №12 Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут 
#и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, 
#значениями которого являются 1, если рецепт простой, и 0 в противном случае.
sim=((data[:,1]<=20) & (data[:,2]<=5))
simp=sim.astype(int)
simpl=np.column_stack((data,simp))
print(simpl[:10])

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 [ 67660      5      6      0]
 [157911     60     14      0]
 [152828     40      7      0]
 [ 33941     18      9      0]
 [446597     15      5      1]
 [366174      7      9      0]
 [ 74205     20      7      0]]


In [88]:
# №13 Выведите процент "простых" рецептов в датасете.
kkk=sum(simpl[:,3]==1)
print((kkk/vsego)*100)

9.552


In [ ]:
# №14 Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность 
#составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; 
#и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, 
#где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), 
#первая ось - за сам рецепт и вторая ось - за характеристики рецепта. 
#Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив.
#Выведите форму полученного массива.